import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cloneElement } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const data = await fetch('https://jsonplaceholder.typicode.com/todos/1').then((response) =>
		response.json()
	)

	return (
		<html lang='en'>
			<body className={inter.className}>{cloneElement(children as any, data)}</body>
		</html>
	)
}
